### PR TITLE
Fix network traffic

### PR DESCRIPTION
**Pull request by Guy-Galil**
This is a fix for SECCON-7437 - Stix to Guardium Query translation fail on network-traffic.
Changes in guardium_report_params.json, guardium_reports_def.json and guard_utils.py were already merged in previous PR for the timezone issue and I am not sure why they show up here again - these are already in the base develop branch.
I also added tests for network-traffic translation.

### CODE REVIEW

**Comment by mdazam1942** [comment]
@Guy-Galil your local branch was outdated. just updated it. now those timezone changes aren't there anymore

**Review by mdazam1942 — COMMENTED** [review]
wondering why `"[network-traffic:dst_ref.value='9.42.54.193']"` translates into two queries but `"[network-traffic:src_ref.value='9.42.54.193']"` translates to one?

**Comment by Guy-Galil** [comment]
> wondering why `"[network-traffic:dst_ref.value='9.42.54.193']"` translates into two queries but `"[network-traffic:src_ref.value='9.42.54.193']"` translates to one?

Guardium has client IP in policy violations but not in threat cases.

**Comment by Guy-Galil** [comment]
@mdazam1942  I removed the comments and removed the function per your comments

**Review by mdazam1942 — APPROVED** [review]

**Review by delliott90 — APPROVED** [review]

**Pull request merged**
