### PR TITLE
Feature adapter cortex

### PR DESCRIPTION
**Pull request by ph34tur3**
Hi,

this is a new adapter to analyze and collect enrichment for STIX2 information by using [Cortex](https://github.com/TheHive-Project/Cortex) to run all available analyzers and get valid STIX2 observed data objects back. It is easily possible to integrate the aggregated data into the existing data structure and therefore provide an easy way to enrich existing STIX2 patterns. 

The resulting objects can be considered as observed data by all requested analyzers, while not necessarily as internally observed data.

**Why this project?**
There is no existing integration between STIX2 data and Cortex. This project aims to empower users to query more than logs or files. Cortex is a centralized aggregation tool (basically a specialized search engine and therefore a data source) that is easily accessible and with this able to enrich STIX2 data.

Thank you for considering. 

Best regards,
ph34tur3

*** The below is required to be filled by any non-IBM employee, in order for their pull request to be accepted ***
DCO 1.1 Signed-off-by: ph34tur3

### CODE REVIEW

**Comment by JasonKeirstead** [comment]
Hi ph34tur3; Due to STIX Shifter being moved into the OCA we have a new process we have to follow before accepting any PRs. Please see above link to digitally sign the required CLA.

Let us know if you have any questions, thanks.

**Comment by JasonKeirstead** [comment]
@ph34tur3 Is there any way you could help with some simple instructions in a README.md or elsewhere for someone not familiar with The Hive in how to use this module? We'd like to give it a shot!

**Comment by ph34tur3** [comment]
@JasonKeirstead 
I will provide some instructions on how to use this module together with Cortex. Currently I am thinking about information on:
- how to set up Cortex (basics)
- how to configure Cortex (basics)
- what parameters to pass when calling stix-shifter
- test files
Any other suggestions?

Best regards,
ph34tur3

**Comment by JasonKeirstead** [comment]
@ph34tur3 yes I think if you can provide that it would be very helpful.

Also feel free to reach out to me on the OCA slack (see link on project page) or via email if you want to have a deeper discussion!

**Comment by ph34tur3** [comment]
@JasonKeirstead : I am currently doing some improvements. I will provide them and the documentation in a few weeks. Thanks!

**Comment by JasonKeirstead** [comment]
Thanks @ph34tur3 .

Another idea to explore is, using STIX Shifter *from* The Hive to run queries and bring back results to enrich incidents.

I am currently working on a simmilar feature for OpenCTI.

**Comment by JasonKeirstead** [comment]
Hey @ph34tur3 - I am very interested in any progress here. Please reach out! You can join our slack on https://opencybersecurityalliance.org/

**Comment by delliott90** [comment]
@ph34tur3 This branch is pretty out of date so I think it's best that we close this. If you pull down the latest develop and port your changes over, you can submit a new pull request and we'll take a look. Closing this out for now and will keep an eye out for a new submission.

**Pull request closed without merging**
