### PR TITLE
adding support for LIKE operator in SumoLogic Module

### LINKED ISSUE #1662: LIKE operator not supported in SumoLogic Module
**Describe the bug**
LIKE operator not supported in SumoLogic module.

With the following query `[process:name LIKE '%powershell%']` you will get this error: `[ERROR] DataSourceError: STIX-shifter translation from STIX to native query failed with message: sumologic connector error => data mapping error : Unable to map the following STIX Operators: [Like] to data source fields`

'%' must become '*' and '_' must become '?' --> https://help.sumologic.com/docs/search/get-started-with-search/search-page/wildcards-in-full-text-searches/

### PR DESCRIPTION
**Pull request by omarrdaniel**
closes #1662

### CODE REVIEW

**Review by mdazam1942 — CHANGES_REQUESTED** [review]
Can you please add a unit test for this change?

**Comment by omarrdaniel** [comment]
Like that?

**Review by mdazam1942 — CHANGES_REQUESTED** [review]
unit test is failing https://github.com/opencybersecurityalliance/stix-shifter/actions/runs/8540116266/job/23397087457?pr=1670#step:6:2176

**Comment by omarrdaniel** [comment]
Maybe i was/am missing some '\' and '"'

**Comment by omarrdaniel** [comment]
Via `stix-shifter-diag`, the following query 
`[domain-name:value LIKE '%example%'] START t'2021-09-01T00:00:00.000Z' STOP t'2021-09-26T10:16:00.000Z'`
get translated in
`{"query": "_sourcehost = *example*", "fromTime": 1630454400000, "toTime": 1632651360000}`

**Comment by omarrdaniel** [comment]
re-edited, now should be good...

**Review by mdazam1942 — APPROVED** [review]

**Pull request merged**
