### PR TITLE
get configs

### PR DESCRIPTION
**Pull request by yurii-klymenko**
python -m main configs
  or
stix-shifter configs

### CODE REVIEW

**Review by mdazam1942 — COMMENTED** [review]
it should have the option to get the config of a specified module as well instead of just getting all the module configs. like this- 

`python main.py configs qradar`

**Comment by yurii-klymenko** [comment]
it is implemented the same way as 
`python -m main modules`
so cli returns for all of them,
but in code you can do:
`config = await stix_tranlation.translate_async('qradar', CONFIGS, {}, {}, {})`
to fetch individual one

**Comment by yurii-klymenko** [comment]
added:
`
python -m main modules 
python -m main modules qradar
python -m main configs
python -m main configs qradar
`

**Review by mdazam1942 — APPROVED** [review]
@yurii-klymenko thanks for adding those extra arguments. looks great

**Pull request merged**
