### PR TITLE
Fix 750

### LINKED ISSUE #750: qradar module does not translate host name and IP in some cases
**Description**
Qradar module does not map the `computer` and `OriginatingComputer` properties that are mapped in many cases to the host name and IP of the computer on which a certain event log occured. Specifically this property is mapped in windows logs.

**To Reproduce**
Consume windows event logs from Qradar. For example:
```<13>Dec 04 12:31:10 XXX-DC1 AgentDevice=WindowsLog      AgentLogFile=Security   PluginVersion=7.3.0.24  Source=Microsoft-Windows-Security-Auditing      Computer=XXX-DC1.YYY.org  OriginatingComputer=1.2.3.4 User=   Domain= EventID=4672    EventIDCode=4672        EventType=8     EventCategory=12548     RecordNumber=16670434   TimeGenerated=1638617468        TimeWritten=1638617468  Level=Log Always        Keywords=Audit Success   Task=SE_ADT_LOGON_SPECIALLOGON  Opcode=Info     Message=Special privileges assigned to new logon.  Subject:  Security ID:  YYY\XXX-WIN-CLIENT2$  Account Name:  XXX-WIN-CLIENT2$  Account Domain:  YYY  Logon ID:  0x2A4013EC  Privileges:  SeSecurityPrivilege    SeBackupPrivilege    SeRestorePrivilege    SeTakeOwnershipPrivilege    SeDebugPrivilege    SeSystemEnvironmentPrivilege    SeLoadDriverPrivilege    SeImpersonatePrivilege    SeEnableDelegationPrivilege```

**Expected behavior**
The value in the `Computer` and `OriginatingComputer` properties should be populated as:
```
"0": {
   "type": "x-oca-asset",
   "hostname": "XXX-DC1.YYY.org",
   "ip_refs": ["1"]
},
"1": {
   "type": "ipv4-addr",
   "value": "1.2.3.4"
}
```

### PR DESCRIPTION
**Pull request by aviv1ron1**
adds `Machine ID` to mappings in aql fields and 
to stix: mapped to `x-oca-asset` `hostname`
from stix: mapped to `x-oca-asset` `hostname`
Closes #750

### CODE REVIEW

**Comment by delliott90** [comment]
@aviv1ron1 can you confirm that these changes will still work with just the Windows and Sysmon QRadar extensions, or will this introduce new QRadar requirements?

**Comment by aviv1ron1** [comment]
@delliott90 yes - this is aligned to the latest version of the `IBM QRadar Custom Properties for Microsoft Windows` version `1.1.7` which introduces the `Machine ID` property which maps the hostname.
As long as the QRadar has this content pack updated it will work.

**Comment by aviv1ron1** [comment]
@delliott90  but I see there are errors in some tests, let me fix those first.

**Comment by aviv1ron1** [comment]
@delliott90  This is ready for merging

**Review by delliott90 — APPROVED** [review]

**Comment by delliott90** [comment]
Looks good, I think I'll open a PR to update the QRadar readme to be explicit on what versions of the extensions are required.

**Pull request merged**
